openrouter:
  model: openai/gpt-4o-mini
  base_url: https://openrouter.ai/api/v1

blacklist_patterns:
  - '\bfind\s+.*\s+(-exec|-execdir|-delete|-quit|-exit)\b' # Dangerous find actions
  - '\btail\s+.*\s+-f\b' # tail -f runs indefinitely
  - '\bgit\s+(commit|push|pull|merge|rebase|reset|clean|checkout|add|rm|stash|tag\s+-d|branch\s+-d|remote\s+(add|remove|rename))\b' # Git state-modifying commands
  - '\bsvn\s+(commit|ci|add|delete|del|remove|rm|copy|cp|move|mv|rename|ren|mkdir|import|switch|sw|merge|resolve|revert|update|up)\b' # SVN state-modifying commands
  - '\b(wget|curl)\s+.*(-o|-O|--output|--output-document)\b' # wget/curl saving output to file
  - '\b(wget|curl)\s+.*(--post-data|--data|-d|--data-raw|--data-binary|--data-urlencode|-F|--form)\b' # wget/curl sending data

  # --- Dangerous Standalone Commands ---
  - '\brm\s+'
  - '\bmv\s+' # Moving/renaming can overwrite or move to sensitive locations
  - '\bcp\s+' # Copying can overwrite (less critical than rm/mv but still risky)
  - '\bdd\s+'
  - '\bshred\s+'
  - '\bmkfs\b'
  - '\bfdisk\b|\bgdisk\b|\bparted\b' # Partitioning tools
  - '\bmount\b'
  - '\bumount\b'

  # --- System Modification & Privilege Escalation ---
  - '\bsudo\b'
  - '\bsu\b'
  - '\b(passwd|chpasswd)\b'
  - '\b(useradd|usermod|userdel)\b'
  - '\b(groupadd|groupmod|groupdel)\b'
  - '\b(chmod|chown|chgrp)\b' # Permissions/ownership changes
  - '\bvisudo\b'
  - '\bsysctl\b'
  - '\b(iptables|nft|firewall-cmd|ufw)\b'
  - '\b(reboot|shutdown|halt|poweroff|init)\b' # System power state

  # --- Package Management (Can run arbitrary scripts, modify system state) ---
  - '\b(apt|apt-get|dpkg|yum|dnf|rpm|pacman|yay|paru|emerge|brew|pkg|nix-env|guix|snap)\s+(remove|purge|reinstall|del|autoremove)\b'
  - '\bpip(\d)?\s+(uninstall|download)\b'
  - '\bnpm\s+(uninstall|un|update|remove|publish)\b'
  - '\byarn\s+(add|remove|upgrade|import)\b'
  - '\b(gem|bundle)\s+(remove)\b'
  - '\bcomposer\s+(remove)\b'

  # --- Service Management ---
  - '\b(systemctl|service|initctl|rcctl|launchctl)\s+(start|stop|restart|reload|enable|disable|mask|unmask|edit)\b'

  # --- Process Killing ---
  - '\b(kill|pkill|killall)\b' # Can disrupt essential services or user work

  # --- Network Connections & Servers (Potential for exfiltration, access, exposure) ---
  - '\b(ssh|scp|sftp)\s+' # Remote connections/transfers
  - '\b(nc|netcat|ncat)\s+' # Versatile networking tool (listen/connect/transfer/scan)
  - '\b(telnet)\s+'

  # --- Direct Execution, Arbitrary Code, Dangerous Interpreters/Compilers ---
  - '\b(sh|bash|zsh|ksh|csh|fish|ash)\s+-c\b' # Executing command string directly in a shell
  - '\b(python|python\d|perl|ruby|node|php|lua|java|javac|gcc|g\+\+|make|./)\s+[\w\.\/-]+' # Running interpreters/compilers directly on arbitrary scripts/files (allow specific safe uses via whitelist if needed)
  - '\beval\b' # Evaluate string as command
  - '\bsource\s+' # Execute commands from a file in current shell

  # --- Dangerous In-place Editing or File Modification ---
  - '\bsed\s+.*\s+(-i|--in-place)\b' # In-place file editing with sed
  - '\bawk\s+.*\b(system\(|getline\s*<)\b' # Awk executing external commands or risky input
  - '\bperl\s+.*(-i)\b' # Perl in-place editing

  # --- Shell ----
  - ";" # Command separator
  - "&&" # Logical AND conditional execution
  - '\|\|' # Logical OR conditional execution
  - '\|'
  - \> # Redirection (overwrite/create) - Block general use
  - \>> # Redirection (append) - Block general use
