# brew "1password-cli"
brew "bat"
brew "chezmoi"
# brew "cloudflared"
brew "eza"
# brew "ffmpeg"
brew "fzf"
brew "gh"
# brew "gnupg"
# brew "jq"
# brew "neovim"
# brew "nmap"
# brew "pinentry-mac"
brew "tailspin"
brew "thefuck"
brew "tlrc"
brew "tmux"
brew "vivid"
brew "wget"
brew "xtermcontrol"
# brew "ykpers"
# brew "yt-dlp"
brew "zoxide"

tap "jandedobbeleer/oh-my-posh"
brew "oh-my-posh"

# cask "ghostty"
